
common: &common
    standalone: true
    disable_token_auth: true
    issue: "Armada dockyard"


local:
    <<: *common
    loglevel: debug
    storage: local
    storage_path: _env:STORAGE_PATH:/repository


s3:
    <<: *common
    loglevel: warn
    storage: s3
    boto_bucket: _env:AWS_S3_BUCKET
    s3_access_key: _env:AWS_ACCESS_KEY
    s3_secret_key: _env:AWS_ACCESS_SECRET
    s3_bucket: _env:AWS_S3_BUCKET
    storage_path: _env:STORAGE_PATH:/
    s3_encrypt: _env:S3_ENCRYPT:false
    s3_secure: _env:S3_USE_HTTPS:true
    storage_redirect: true
